version: "3"
services:
  database:
    image: "postgres" # use latest official postgres version
    env_file:
      - database.env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    networks:
      - neural
    ports:
      - "5432:5432"

  vis_collector:
    build: ./collector
    depends_on:
      - database
    networks:
      - neural
    ports:
      - "4321:4321"

  visualiser:
    build: ./visualiser
    depends_on:
      - vis_collector
    command:
      [
        "./wait-for-it.sh",
        "collector:4321",
        "-t",
        "10",
        "--",
        "node",
        "server.js",
      ]
    networks:
      - neural
    ports:
      - "8080:8080"

volumes:
  database-data: # named volumes can be managed easier using docker-compose

networks:
  neural:
    driver: bridge
