version: "3"
services:
  database:
    image: "postgres" # use latest official postgres version
    env_file:
      - database.env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    networks:
      - neural
    ports:
      - "5432:5432"

  collector:
    build: ./collector
    command: tail -F anything
    depends_on:
      - database
    networks:
      - neural

  cleaner:
    build: ./cleaner
    command: tail -F anything
    depends_on:
      - database
    networks:
      - neural

  visualiser:
    build: ./visualiser
    depends_on:
      - database
    networks:
      - neural
    ports:
      - "8080:8080"

volumes:
  database-data: # named volumes can be managed easier using docker-compose

networks:
  neural:
    driver: bridge
