# This is a basic workflow to help you get started with Actions

name: CI-compose

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
      

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@main

      # Runs a single command using the runners shell
      - name: Installing dependencies
        run: |
          pip3 install setuptools
          pip3 install pytest
          pip3 install -r collector/requirements.txt
          npm config set user 0
          npm config set unsafe-perm true
          npm install jest
          
      
      - name: Testing collector
        run: python3 -m pytest collector/test_data_collector.py::test_rating_data_download
        
      - name: Testing visualiser
        run: |
          cd visualiser
          npm install
          npm run build --if-present
          npm test
                 

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          cd ..
          docker-compose up -d
        
      - name: Wait 10s
        run: sleep 10
        
      - name: Currently running contaioners
        run: docker ps
        
        
      - name: History of all contaioners
        run: docker ps -a
        
